### ISSUE TITLE
Modified $cell-horizontal-border not taken into account

### ISSUE THREAD

**Issue by DGothrek** [ag-grid/ag-grid-customise-theme#4]
Hello there,

I am trying to build an excel-like custom theme, and I have an issue with some parameters that the modification does not take into account.
I have followed the model you give in this repo, and I would like to change the `cell-horizontal-border` and `border-color` color to red for testing purposes. Below is my style.scss file.

```scss{22}
// Customize the look and feel of the grid with Sass variables
// Up-to-date list of variables is available in the source code: https://github.com/ag-grid/ag-grid/blob/latest/src/styles/theme-fresh.scss

// Temporary, due to bug in 17.0.0. should use only $icons-path:  "~ag-grid/src/styles/material-icons/"
$icons-path: "~ag-grid/src/styles/icons/";
$ag-mat-icons-path: "~ag-grid/src/styles/icons/";

// changes the border color
$border-color: red;

// Changes the font size
$font-size: 12px;

// Reverts the cell horizontal padding change between ag-fresh and ag-theme-fresh
$cell-horizontal-padding: 2px;

// changes the default icon color
$icon-color: #303f9f;

$row-height: 20px;
$cell-horizontal-border: 2px dotted red;

//$odd-row-background-color: white;

@import "~ag-grid/src/styles/ag-grid.scss";
@import "~ag-grid/src/styles/ag-theme-material.scss";

html,
body {
  height: 100%;
}

```

Here is the result:

![screenshot from 2018-07-24 14-24-13](https://user-images.githubusercontent.com/35027141/43137859-5b625422-8f4d-11e8-8470-46f6bbd2ab3c.png)

As you see, the `$border-color` has been correctly processed but not the `$cell-horizontal-border`.
When modifying the bootstrap theme with the same params, it gives the following result:

![screenshot from 2018-07-24 14-26-49](https://user-images.githubusercontent.com/35027141/43137964-b72cdebc-8f4d-11e8-95e1-e4df499a78b8.png)

Thus, it seems that only the variables that are taken into account in the scss builder of that theme are relevant here. Thus it is impossible for me to set `border-color` and `cell-horizontal-border` at the same time in any theme.

Is it a wanted behavior ? Any idea on how I could fix it ?
